POST http://localhost:5000/api/url/shorten
Content-Type: application/json

{
    "longUrl": "https://tiki.vn/vien-sui-bo-sung-vitamin-c-d-va-kem-redoxon-triple-action-10-vien-p46082769.html?spid=46082770"
}